---
on:
  push:

concurrency: unique

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: First interaction update
        timeout-minutes: 5
        run: sleep 180
