---
name: release

on:
  push:

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: gh release list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
