---
on:
  push:

concurrency:
  group: unique
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: First interaction update
        timeout-minutes: 5
        # run: sleep 180
        run: echo 1
